### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Hanhesong** [TzuChiangLi/WanAndroid#1]
使用夜神模拟器安装项目后，首页第一篇置顶文章无法收藏，其他可以。

**Comment by TzuChiangLi** [comment]
我使用AS自己的模拟器还有一些真机测试是可以的，谢谢你的反馈，我会在确定问题出现位置后立即修复。

**Comment by Hanhesong** [comment]
我当天试了几次，都出现了首页列表第一个点不了收藏的bug，但后来就又OK了。应该是我这里的原因。

TzuChiangLi <notifications@github.com> 于2019年7月7日周日 下午2:05写道：

**Comment by TzuChiangLi** [comment]
嗯嗯，谢谢你的反馈！



724581911@qq.com
 
From: Hanhesong
Date: 2019-07-08 09:25
To: TzuChiangLi/WanAndroid
CC: TzuChiangLi; Comment
Subject: Re: [TzuChiangLi/WanAndroid] bug (#1)
我当天试了几次，都出现了首页列表第一个点不了收藏的bug，但后来就又OK了。应该是我这里的原因。 

TzuChiangLi <notifications@github.com> 于2019年7月7日周日 下午2:05写道：
